"""Fix organizer_emails.booking_ids and recipient_emails to be real array columns

Revision ID: 21244b5987a7
Revises: a761537500dc
Create Date: 2026-07-28 02:32:54.597731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21244b5987a7'
down_revision: Union[str, Sequence[str], None] = 'a761537500dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # Autogenerate missed the booking_ids type change entirely (a known
    # quirk: BigInteger -> ARRAY(BigInteger) doesn't always get flagged the
    # way TEXT -> ARRAY(String) does), and neither alter had a USING clause
    # — Postgres has no implicit scalar->array cast, so both need one to
    # actually run. Existing scalar values are wrapped into single-element
    # arrays rather than discarded, so no data is lost on upgrade.
    op.alter_column(
        'organizer_emails', 'booking_ids',
        existing_type=sa.BigInteger(),
        type_=postgresql.ARRAY(sa.BigInteger()),
        existing_nullable=True,
        postgresql_using="CASE WHEN booking_ids IS NULL THEN NULL ELSE ARRAY[booking_ids] END",
    )
    op.alter_column(
        'organizer_emails', 'recipient_emails',
        existing_type=sa.TEXT(),
        type_=postgresql.ARRAY(sa.String(length=150)),
        existing_nullable=True,
        postgresql_using="CASE WHEN recipient_emails IS NULL THEN NULL ELSE ARRAY[recipient_emails] END",
    )
    op.alter_column('payments', 'manual_review_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'manual_review_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'none'::character varying"),
               existing_nullable=False)
    # Reverse order of upgrade(). Lossy only if a row ever holds more than
    # one booking_id / recipient_email — array[1] keeps just the first.
    op.alter_column(
        'organizer_emails', 'recipient_emails',
        existing_type=postgresql.ARRAY(sa.String(length=150)),
        type_=sa.TEXT(),
        existing_nullable=True,
        postgresql_using="array_to_string(recipient_emails, ',')",
    )
    op.alter_column(
        'organizer_emails', 'booking_ids',
        existing_type=postgresql.ARRAY(sa.BigInteger()),
        type_=sa.BigInteger(),
        existing_nullable=True,
        postgresql_using="booking_ids[1]",
    )
    # ### end Alembic commands ###