"""Add event title field to contact messages

Revision ID: 259a35f35749
Revises: f227bc8455ce
Create Date: 2026-06-01 10:19:33.337650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259a35f35749'
down_revision: Union[str, Sequence[str], None] = 'f227bc8455ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('event_title', sa.String(length=200), nullable=True))
    op.drop_column('contact_messages', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('event_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('contact_messages', 'event_title')
    # ### end Alembic commands ###
