"""Update is_active field in the in the events table

Revision ID: 2f79d6580a6f
Revises: dbeb5c4db7da
Create Date: 2026-06-21 06:43:23.133544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79d6580a6f'
down_revision: Union[str, Sequence[str], None] = 'dbeb5c4db7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
