"""add organizer email related table

Revision ID: 45983943cf62
Revises: 5e2e54decb28
Create Date: 2026-02-28 01:30:08.968643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45983943cf62'
down_revision: Union[str, Sequence[str], None] = '5e2e54decb28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizer_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('recipient_type', sa.String(length=50), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('template_used', sa.String(length=50), nullable=False),
    sa.Column('booking_ids', sa.BigInteger(), nullable=True),
    sa.Column('recipient_emails', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_emails_booking_ids'), 'organizer_emails', ['booking_ids'], unique=False)
    op.create_index(op.f('ix_organizer_emails_created_at'), 'organizer_emails', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizer_emails_event_id'), 'organizer_emails', ['event_id'], unique=False)
    op.create_index(op.f('ix_organizer_emails_id'), 'organizer_emails', ['id'], unique=False)
    op.create_index(op.f('ix_organizer_emails_organizer_id'), 'organizer_emails', ['organizer_id'], unique=False)
    op.create_index(op.f('ix_organizer_emails_status'), 'organizer_emails', ['status'], unique=False)
    op.create_table('organizer_email_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_email', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['email_id'], ['organizer_emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizer_email_recipients_booking_id'), 'organizer_email_recipients', ['booking_id'], unique=False)
    op.create_index(op.f('ix_organizer_email_recipients_created_at'), 'organizer_email_recipients', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizer_email_recipients_email_id'), 'organizer_email_recipients', ['email_id'], unique=False)
    op.create_index(op.f('ix_organizer_email_recipients_id'), 'organizer_email_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_organizer_email_recipients_status'), 'organizer_email_recipients', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizer_email_recipients_status'), table_name='organizer_email_recipients')
    op.drop_index(op.f('ix_organizer_email_recipients_id'), table_name='organizer_email_recipients')
    op.drop_index(op.f('ix_organizer_email_recipients_email_id'), table_name='organizer_email_recipients')
    op.drop_index(op.f('ix_organizer_email_recipients_created_at'), table_name='organizer_email_recipients')
    op.drop_index(op.f('ix_organizer_email_recipients_booking_id'), table_name='organizer_email_recipients')
    op.drop_table('organizer_email_recipients')
    op.drop_index(op.f('ix_organizer_emails_status'), table_name='organizer_emails')
    op.drop_index(op.f('ix_organizer_emails_organizer_id'), table_name='organizer_emails')
    op.drop_index(op.f('ix_organizer_emails_id'), table_name='organizer_emails')
    op.drop_index(op.f('ix_organizer_emails_event_id'), table_name='organizer_emails')
    op.drop_index(op.f('ix_organizer_emails_created_at'), table_name='organizer_emails')
    op.drop_index(op.f('ix_organizer_emails_booking_ids'), table_name='organizer_emails')
    op.drop_table('organizer_emails')
    # ### end Alembic commands ###
