"""add max_per_booking to ticket_types

Revision ID: 5cfc7129e042
Revises: 80dd362a2c36
Create Date: 2026-07-21 22:11:05.929226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cfc7129e042'
down_revision: Union[str, Sequence[str], None] = '80dd362a2c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('max_per_booking', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_types', 'max_per_booking')
    # ### end Alembic commands ###
