"""Change quantity_available to total_quantity in the ticket_type table for the second time

Revision ID: 6e09025b3a38
Revises: 7e3d803618f7
Create Date: 2026-01-27 13:51:48.421870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e09025b3a38'
down_revision: Union[str, Sequence[str], None] = '7e3d803618f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('total_quantity', sa.Integer(), nullable=False))
    op.drop_column('ticket_types', 'quantity_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('quantity_available', sa.INTEGER(), nullable=False))
    op.drop_column('ticket_types', 'total_quantity')
    # ### end Alembic commands ###
