"""Change quantity_available to total_quantity in the ticket_type table

Revision ID: 7e3d803618f7
Revises: 29075d01bb9d
Create Date: 2026-01-27 13:49:25.391876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3d803618f7'
down_revision: Union[str, Sequence[str], None] = '29075d01bb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_types', 'is_active')
    # ### end Alembic commands ###
