"""Add ticket type suspension fields

Revision ID: 80dd362a2c36
Revises: bd3fffb138c8
Create Date: 2026-07-07 13:32:53.386528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dd362a2c36'
down_revision: Union[str, Sequence[str], None] = 'bd3fffb138c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_types', sa.Column('suspended_by_admin_id', sa.Integer(), nullable=True))
    op.add_column('ticket_types', sa.Column('suspended_by_admin_name', sa.String(length=150), nullable=True))
    op.add_column('ticket_types', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    op.add_column('ticket_types', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'ticket_types', 'users', ['suspended_by_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_types', type_='foreignkey')
    op.drop_column('ticket_types', 'suspended_at')
    op.drop_column('ticket_types', 'suspension_reason')
    op.drop_column('ticket_types', 'suspended_by_admin_name')
    op.drop_column('ticket_types', 'suspended_by_admin_id')
    # ### end Alembic commands ###
