"""add manual payment review fields

Revision ID: a761537500dc
Revises: 5cfc7129e042
Create Date: 2026-07-23 05:39:19.980497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a761537500dc'
down_revision: Union[str, Sequence[str], None] = '5cfc7129e042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('manual_review_status', sa.String(length=20), nullable=False, server_default='none'))
    op.add_column('payments', sa.Column('user_reported_mpesa_code', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('user_reported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'user_reported_at')
    op.drop_column('payments', 'user_reported_mpesa_code')
    op.drop_column('payments', 'manual_review_status')
    # ### end Alembic commands ###
