"""add article related tables

Revision ID: a8a80a063bb5
Revises: 2cf02582703b
Create Date: 2026-01-12 01:23:41.719106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a80a063bb5'
down_revision: Union[str, Sequence[str], None] = '2cf02582703b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_slug', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('scroll_depth_percent', sa.Integer(), nullable=False),
    sa.Column('engaged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_engagements_id'), 'article_engagements', ['id'], unique=False)
    op.create_table('article_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_slug', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('feedback_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_intent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_feedback_article_slug'), 'article_feedback', ['article_slug'], unique=False)
    op.create_index(op.f('ix_article_feedback_id'), 'article_feedback', ['id'], unique=False)
    op.create_table('article_search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('clicked_article_slug', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_search_queries_id'), 'article_search_queries', ['id'], unique=False)
    op.create_table('article_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_slug', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('referrer', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_views_id'), 'article_views', ['id'], unique=False)
    op.drop_constraint(None, 'contact_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contact_messages', 'users', ['assigned_to'], ['id'])
    op.drop_index(op.f('ix_article_views_id'), table_name='article_views')
    op.drop_table('article_views')
    op.drop_index(op.f('ix_article_search_queries_id'), table_name='article_search_queries')
    op.drop_table('article_search_queries')
    op.drop_index(op.f('ix_article_feedback_id'), table_name='article_feedback')
    op.drop_index(op.f('ix_article_feedback_article_slug'), table_name='article_feedback')
    op.drop_table('article_feedback')
    op.drop_index(op.f('ix_article_engagements_id'), table_name='article_engagements')
    op.drop_table('article_engagements')
    # ### end Alembic commands ###
