"""Update booking, payment and ticket instance and type

Revision ID: aab37cdffb7e
Revises: 259a35f35749
Create Date: 2026-06-11 17:19:49.046203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aab37cdffb7e'
down_revision: Union[str, Sequence[str], None] = '259a35f35749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('mpesa_phone', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('mpesa_checkout_request_id', sa.String(length=200), nullable=True))
    op.alter_column('payments', 'mpesa_ref',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'mpesa_ref',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('payments', 'mpesa_checkout_request_id')
    op.drop_column('payments', 'mpesa_phone')
    # ### end Alembic commands ###
