"""add scanned_by and scan_method to the ticket_instance model

Revision ID: bd3fffb138c8
Revises: aa194dd48302
Create Date: 2026-07-05 12:54:22.734654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd3fffb138c8'
down_revision: Union[str, Sequence[str], None] = 'aa194dd48302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_instances', sa.Column('scanned_by', sa.String(length=150), nullable=True))
    op.add_column('ticket_instances', sa.Column('scan_method', sa.String(length=20), nullable=True))
    op.alter_column('users', 'area_of_expertise',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'area_of_expertise',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('ticket_instances', 'scan_method')
    op.drop_column('ticket_instances', 'scanned_by')
    # ### end Alembic commands ###
