"""Add notification table foreign key to users table

Revision ID: cb16f1166a1b
Revises: c4280155253a
Create Date: 2026-05-25 05:13:57.700589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb16f1166a1b'
down_revision: Union[str, Sequence[str], None] = 'c4280155253a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.create_foreign_key(
            'fk_notifications_recipient_id_users',
            'users',
            ['recipient_id'],
            ['id']
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications') as batch_op:
        batch_op.drop_constraint(
            'fk_notifications_recipient_id_users',
            type_='foreignkey'
        )
