"""add client_ip to article_views

Revision ID: cee83a2ad926
Revises: 21244b5987a7
Create Date: 2026-08-02 06:45:20.616143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee83a2ad926'
down_revision: Union[str, Sequence[str], None] = '21244b5987a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_views', sa.Column('client_ip', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_views', 'client_ip')
    # ### end Alembic commands ###
