"""Streamline relationship between users and events table

Revision ID: dbeb5c4db7da
Revises: f0b685bb3a4a
Create Date: 2026-06-21 01:15:06.896995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbeb5c4db7da'
down_revision: Union[str, Sequence[str], None] = 'f0b685bb3a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'commission_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='platform_default | negotiated',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'commission_source',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'platform_default'::character varying"),
               existing_comment='platform_default | negotiated',
               existing_nullable=False)
    # ### end Alembic commands ###
