"""add ondelete rules to event-related foreign keys

Revision ID: dd392e86052d
Revises: 2f79d6580a6f
Create Date: 2026-06-25 01:23:03.542212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd392e86052d'
down_revision: Union[str, Sequence[str], None] = '2f79d6580a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('co_organizers_event_id_fkey'), 'co_organizers', type_='foreignkey')
    op.drop_constraint(op.f('co_organizers_user_id_fkey'), 'co_organizers', type_='foreignkey')
    op.create_foreign_key(None, 'co_organizers', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'co_organizers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.drop_constraint(op.f('favorites_event_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'favorites', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organizer_emails_event_id_fkey'), 'organizer_emails', type_='foreignkey')
    op.create_foreign_key(None, 'organizer_emails', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('ticket_types_event_id_fkey'), 'ticket_types', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_types', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_types', type_='foreignkey')
    op.create_foreign_key(op.f('ticket_types_event_id_fkey'), 'ticket_types', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'organizer_emails', type_='foreignkey')
    op.create_foreign_key(op.f('organizer_emails_event_id_fkey'), 'organizer_emails', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_event_id_fkey'), 'favorites', 'events', ['event_id'], ['id'])
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'co_organizers', type_='foreignkey')
    op.drop_constraint(None, 'co_organizers', type_='foreignkey')
    op.create_foreign_key(op.f('co_organizers_user_id_fkey'), 'co_organizers', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('co_organizers_event_id_fkey'), 'co_organizers', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
