"""Add refresh_session table

Revision ID: e68a0ae62016
Revises: f2975644bea6
Create Date: 2025-12-20 22:40:35.329813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68a0ae62016'
down_revision: Union[str, Sequence[str], None] = 'f2975644bea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('event_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'event_id')
    # ### end Alembic commands ###
