"""Add city field to the events table

Revision ID: f227bc8455ce
Revises: 1cd0d22db9af
Create Date: 2026-06-01 06:29:57.322938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f227bc8455ce'
down_revision: Union[str, Sequence[str], None] = '1cd0d22db9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('contact_messages', sa.Column('event_id', sa.String(length=50), nullable=True))
    op.alter_column('contact_messages', 'reference_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('contact_messages', 'user_agent',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('contact_messages', 'recaptcha_score',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               postgresql_using='recaptcha_score::double precision',
               existing_nullable=True)
    op.create_index(op.f('ix_contact_messages_source'), 'contact_messages', ['source'], unique=False)
    op.add_column('events', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_active')
    op.drop_column('events', 'category')
    op.drop_column('events', 'city')
    op.drop_index(op.f('ix_contact_messages_source'), table_name='contact_messages')
    op.alter_column('contact_messages', 'recaptcha_score',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('contact_messages', 'user_agent',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('contact_messages', 'reference_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('contact_messages', 'event_id')
    op.drop_column('contact_messages', 'source')
    # ### end Alembic commands ###
