"""modify organizer info to users

Revision ID: f2975644bea6
Revises: 09cfa1f7b1ed
Create Date: 2025-12-07 07:30:14.604495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2975644bea6'
down_revision: Union[str, Sequence[str], None] = '09cfa1f7b1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_instances', sa.Column('seat_number', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('website_url', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('social_media_links', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('area_of_expertise', sa.String(length=200), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('users', 'area_of_specialty')
    op.drop_column('users', 'website')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('website', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('area_of_specialty', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'area_of_expertise')
    op.drop_column('users', 'social_media_links')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'website_url')
    op.drop_column('ticket_instances', 'seat_number')
    # ### end Alembic commands ###
