"""Change backref to back_populates in notifications table

Revision ID: fb01d7e21ba4
Revises: cb16f1166a1b
Create Date: 2026-05-25 05:25:36.694180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb01d7e21ba4'
down_revision: Union[str, Sequence[str], None] = 'cb16f1166a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
