"""Updating User Table with Organizer Info

Revision ID: 54b350d51ff7
Revises: b989f6b4670a
Create Date: 2025-11-24 04:29:43.317378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54b350d51ff7'
down_revision: Union[str, Sequence[str], None] = 'b989f6b4670a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('organization_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('area_of_specialty', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'area_of_specialty')
    op.drop_column('users', 'tax_id')
    op.drop_column('users', 'address')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'website')
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
