#!/usr/bin/env python3
"""
Ticket QR signing utilities for MGLTickets.

Each ticket instance's QR code encodes a small signed JSON payload rather
than the bare ticket code. The HMAC signature lets the check-in endpoint
reject forged or corrupted QR images with zero DB hits. It is NOT a
substitute for the atomic conditional UPDATE in check_in_ticket_instance_repo
— a valid signature proves "generated by us at issuance time", not "still
unused". The used/unused decision belongs to the DB alone.
"""

import hashlib
import hmac
import json
from typing import Optional, TypedDict

from app.core.config import TICKET_QR_SECRET

# 16 hex chars = 64 bits of signature entropy — infeasible to forge while
# keeping the QR payload compact enough to scan reliably.
_SIG_LEN = 16


class TicketQrPayload(TypedDict):
    c: str   # ticket code      e.g. "TKT-101-A3F9B2C1"
    t: int   # ticket_instance.id
    e: int   # event_id (stored directly on ticket_instance)
    s: str   # truncated HMAC-SHA256 signature


def _sign(code: str, ticket_instance_id: int, event_id: int) -> str:
    """HMAC-SHA256 over 'code|ticket_instance_id|event_id', truncated to
    _SIG_LEN hex chars. Field order is fixed — both signing and verification
    must use this exact concatenation."""
    message = f"{code}|{ticket_instance_id}|{event_id}".encode()
    full = hmac.new(TICKET_QR_SECRET.encode(), message, hashlib.sha256).hexdigest()
    return full[:_SIG_LEN]


def build_ticket_qr_payload(
    code: str,
    ticket_instance_id: int,
    event_id: int,
) -> str:
    """
    Build the compact signed JSON string to embed in a ticket's QR code.

    Called from _build_out() in ticket_instance_repo.py on every read —
    cheap (one HMAC call) and avoids a separate DB column or migration.

    Example output:
        {"c":"TKT-101-A3F9B2C1","t":4821,"e":17,"s":"9f2a1b7e4c3d8a01"}
    """
    payload: TicketQrPayload = {
        "c": code,
        "t": ticket_instance_id,
        "e": event_id,
        "s": _sign(code, ticket_instance_id, event_id),
    }
    return json.dumps(payload, separators=(",", ":"))


def verify_ticket_qr_payload(raw: str) -> Optional[TicketQrPayload]:
    """
    Parse and verify a scanned QR string.

    Returns the parsed payload dict if the HMAC is valid, None otherwise.
    None means immediate, zero-DB-hit rejection at the check-in endpoint.
    Uses hmac.compare_digest to prevent timing attacks.
    """
    try:
        data = json.loads(raw)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(data, dict):
        return None

    c = data.get("c")
    t = data.get("t")
    e = data.get("e")
    s = data.get("s")

    if not (isinstance(c, str) and isinstance(t, int)
            and isinstance(e, int) and isinstance(s, str)):
        return None

    if not hmac.compare_digest(_sign(c, t, e), s):
        return None

    return {"c": c, "t": t, "e": e, "s": s}